apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
spec:
  selector:
    matchLabels:
      app: library
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
      - name: libraryservice
        image: libraryservice
        env:
        - name: MYSQL_URL_PATH
          value: "mysql/books?useSSL=false"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 8081
          name: library
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: library
spec:
  ports:
  - port: 8081
  selector:
    app: library